#!/usr/bin/env python3

"""
This code defines a script which backs up the royal repos.
"""

# Bespoke imports.
from hosker_utils.royal_repos_backup import back_up_royal_repos

###################
# RUN AND WRAP UP #
###################

def run():
    """ Run this file. """
    back_up_royal_repos()

if __name__ == "__main__":
    run()
